// <auto-generated />
using DataAccess.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(ContextContext))]
    [Migration("20191028225453_assdff")]
    partial class assdff
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("Name");

                    b.Property<int>("SchoolNumber");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.ToTable("Student");

                    b.HasData(
                        new { Id = 1, Age = 15, Name = "Azra", SchoolNumber = 222, Surname = "Yerli" },
                        new { Id = 2, Age = 23, Name = "Hazal", SchoolNumber = 333, Surname = "Yerli" },
                        new { Id = 3, Age = 26, Name = "Parla", SchoolNumber = 444, Surname = "Yerli" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
